### ISSUE TITLE
window.atob is not defined in node

### ISSUE THREAD

**Issue by mbasso** [pine/arraybuffer-loader#2]
Hi,
I'm using this library with webpack to load `.wasm` files that need to be executed both on the client and on the server. It works fine on the client, but if I try to execute the code on the server I receive the following error:

`TypeError: window.atob is not a function`

I think that the problem might be [here](https://github.com/pine/arraybuffer-loader/blob/master/lib/to-array-buffer.js#L5). Do you think that we can fix that using [this package](https://www.npmjs.com/package/atob) if `window.atob` is not defined?

**Comment by mbasso** [comment]
Otherwise we can just preprocess the data to avoid runtime computation, creating the decoded string and the char codes at compile time. I think that we can delete the [to-array-buffer.js](https://github.com/pine/arraybuffer-loader/blob/ea30e2ad1dd822e234578e48be63a6ebe3e55128/lib/to-array-buffer.js) file and update the [arraybuffer-loader.js](https://github.com/pine/arraybuffer-loader/blob/ea30e2ad1dd822e234578e48be63a6ebe3e55128/lib/arraybuffer-loader.js) as follow:

```js
const binary = require('atob')(base64Data);
const charCodes = binary.split('').map(char => char.charCodeAt(0));
return `module.exports = new Uint8Array(${JSON.stringify(charCodes)}).buffer`;
```
What do you think about that?

**Comment by pine** [comment]
@mbasso Thank you your bug reports!

> TypeError: window.atob is not a function

Oh, this is problem.

Your suggestion are resolve this problem, but it make large output.
I'll research other WebPack plugins.

Thank you.

**Comment by pine** [comment]
I've found this code. I'll try it later.
https://github.com/node-browser-compat/atob/blob/master/node-atob.js

**Comment by mbasso** [comment]
> Thank you your bug reports!

Thank you for your effort on this loader 😄 

> Your suggestion are resolve this problem, but it make large output.
I'll research other WebPack plugins.

Yes, unfortunately that's true, they both make a larger output.

> I've found this code. I'll try it later.
https://github.com/node-browser-compat/atob/blob/master/node-atob.js

awesome! It seems perfect!

**Comment by pine** [comment]
@mbasso Hello. I've supported node, and published new version v1.0.0 👍
https://www.npmjs.com/package/arraybuffer-loader

Thank you 🎊

**Comment by mbasso** [comment]
@pine Awesome! Thank you a lot, I'll update and try it out this night 😄

**Comment by pine** [comment]
@mbasso Did I help you? Please add star if you like. 😊

**Comment by mbasso** [comment]
Yes, it works fine, thank you very much 😄 starred! ⭐️
