### ISSUE TITLE
Use u8str inlining for compression

### ISSUE THREAD

**Issue by ghost** [pine/arraybuffer-loader#51]
As shown in pawsong/bin-loader#1 , we could:
- inline a u8str instead of a base64
- convert back to array (codepoint/char stream)
- then bypass any base-64 maximum length.

Perf-wise, this brings little if any impact.

https://github.com/pine/arraybuffer-loader/blob/7236c497faf1d059dc1117976eb7416f59abd976/lib/to-array-buffer.js#L5

**Comment by ghost** [comment]
```javascript
/* u8arr to u8str compression */
function decodePointToHex(x) { return x.toString(16).padStart(2, '0'); }

/** u8str to u8arr decompression */
const encodeHexToPoint = 'function encodeHexToPoint(_, i) { return parseInt(this.charAt(2 * i) + this.charAt(2 * i + 1), 16); }';
```

**Comment by pine** [comment]
Hello @M00TSDNS, thank you for your suggestion.

Could you tell me the specific compression ratio when compared to your proposed method and base64?

e.g.
```
Original Data: 100% (xxx bytes)
Base64: 80%
Your proposed method: 70%
```

**Comment by ghost** [comment]
I will open draft PR and gen that info today

**Comment by ghost** [comment]
BTOA appears to be increasing sizes a little, whereas my Encoding API-style zero pads about 1/3 of the chars.  
This package is doing much better than `bin-loader` in any case.. that bundles up a utf8 json array

**Comment by ghost** [comment]
The package distinctly does not like wasm however.. it's because wasm uses characters outside ascii range. 
Coercing a Uint8 (= 256) buffer to Base64 (64) could probably force a bit shift that damages integrity  
I suppose the users of #12 can consume `encoded-uint8array-loader` and take the 50% data hit (going up from 133% to 200%).

**Comment by ghost** [comment]
If you wish we can invest in https://www.npmjs.com/package/byte-base64 and it will fix WASM
